# Generated by Django 3.2.4 on 2021-06-11 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ادرس لینک')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='منتشر شده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروز رسانی شده')),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
